export enum SocketEvents {
    CreateRoom = 'createRoom',
    StartGame = 'startGame',
    BroadcastAll = 'broadcastAll',
    JoinRoom = 'joinRoom',
    LeaveRoom = 'leaveRoom',
    CreatePlayer = 'createPlayer',
    SelectCharacter = 'selectCharacter',
    ChangeLockRoom = 'changeLockRoom',
    IsLocked = 'isLocked',
    GetMap = 'getMap',
    SendMessage = 'sendMessages',
    EndTurn = 'endTurn',
    StartTurn = 'startTurn',
    BeforeStartTurn = 'beforeStartTurn',
    PlayerNavigation = 'playerNavigation',
    KickPlayer = 'kickPlayer',
    SendGameLog = 'sendGameLog',
    StartFight = 'startFight',
    AttackPlayer = 'attackPlayer',
    EvadeCombat = 'evadeCombat',
    DoorClicked = 'doorClicked',
    EndGame = 'endGame',
    DebugMode = 'debugMode',
    TeleportPlayer = 'teleportPlayer',
}
