export enum SocketEvents {
    CreateRoom = 'createRoom',
    StartGame = 'startGame',
    BroadcastAll = 'broadcastAll',
    JoinRoom = 'joinRoom',
    LeaveRoom = 'leaveRoom',
    CreatePlayer = 'createPlayer',
    SelectCharacter = 'selectCharacter',
    ChangeLockRoom = 'changeLockRoom',
    IsLocked = 'isLocked',
    GetMap = 'getMap',
    SendMessage = 'sendMessages',
    EndTurn = 'endTurn',
    StartTurn = 'startTurn',
    BeforeStartTurn = 'beforeStartTurn',
    StartFight = 'startFight',
    EndFight = 'endFight',
    PlayerNavigation = 'playerNavigation',
}
