export enum SocketEvents {
    CreateRoom = 'createRoom',
    StartGame = 'startGame',
    BroadcastAll = 'broadcastAll',
    JoinRoom = 'joinRoom',
    LeaveRoom = 'leaveRoom',
    CreatePlayer = 'createPlayer',
    SelectCharacter = 'selectCharacter',
    ChangeLockRoom = 'changeLockRoom',
    IsLocked = 'isLocked',
    GetMap = 'getMap',
    SendMessage = 'sendMessages',
    EndTurn = 'endTurn',
    StartTurn = 'startTurn',
    BeforeStartTurn = 'beforeStartTurn',
    PlayerNavigation = 'playerNavigation',
    KickPlayer = 'kickPlayer',
    GameLog = 'GameLog',
    StartFight = 'startFight',
    AttackPlayer = 'attackPlayer',
    EvadeCombat = 'evadeCombat',
    EndGame = 'endGame',
    CreateBot = 'createBot',
    KickBot = 'kickBot',
    DoorAction = 'doorAction',
    DebugMode = 'debugMode',
    TeleportPlayer = 'teleportPlayer',
}
