import { ITEM_COUNT, ObjectType } from '@app/constants';
import { GameObject } from './interfaces/game-object';

export const gameObjects: GameObject[] = [
    {
        id: ObjectType.Trident,
        name: 'Trident de Poséidon',
        image: './assets/images/objects/poseidon-trident.jpg',
        description: 'Modifie le dé du joueur qui équipe cet objet : les valeurs équiprobables possibles sont 1, 2, 3, 5, 6, 6',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Armor,
        name: 'Armure de Achilles',
        image: './assets/images/objects/armor-of-achilles.jpg',
        description: '+3 défense',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Sandal,
        name: 'Sandales ailées',
        image: './assets/images/objects/winged-sandals.jpg',
        description: 'x2 rapidité si les points de vie actuels du jouer est inférieur ou égal à 33% de ses points de vie totaux',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Lightning,
        name: 'Foudre de Zeus',
        image: './assets/images/objects/zeus-lightning.jpg',
        description: 'x1.5 attaque',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Xiphos,
        name: 'Xiphos',
        image: './assets/images/objects/xiphos.jpg',
        description: 'Si les points de vie actuels du joueur qui équipe cet objet est égale ou inférieure à 50% de son PV maximal, +4 attaque',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Kunee,
        name: 'kunée',
        image: './assets/images/objects/helm-of-darkness.jpg',
        description: 'Vole 1 vie de chaque autre joueur',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Random,
        name: 'Random Item',
        image: './assets/images/objects/dice.jpg',
        description: 'Ajoute un item aléatoire',
        count: -1,
    },
    {
        id: ObjectType.Spawn,
        name: 'Point de départ',
        image: './assets/images/objects/tree.jpg',
        description: 'Désigne le point de départ du jouer',
        count: -1,
    },
    {
        id: ObjectType.Hestia,
        name: 'Hestia',
        image: './assets/images/characters/Hestia.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Zeus,
        name: 'Zeus',
        image: './assets/images/characters/Zeus.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Hera,
        name: 'Hera',
        image: './assets/images/characters/Hera.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Poseidon,
        name: 'Poseidon',
        image: './assets/images/characters/Poseidon.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Artemis,
        name: 'Artemis',
        image: './assets/images/characters/Artemis.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Demeter,
        name: 'Demeter',
        image: './assets/images/characters/Demeter.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Hermes,
        name: 'Hermes',
        image: './assets/images/characters/Hermes.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Athena,
        name: 'Athena',
        image: './assets/images/characters/Athena.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Hephaestus,
        name: 'Hephaestus',
        image: './assets/images/characters/Hephaestus.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Apollo,
        name: 'Apollo',
        image: './assets/images/characters/Apollo.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Ares,
        name: 'Ares',
        image: './assets/images/characters/Ares.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Aphrodite,
        name: 'Aphrodite',
        image: './assets/images/characters/Aphrodite.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
];
