enum TileType {
    Ground = 1,
    Ice = 2,
    Water = 3,
    Wall = 4,
    ClosedDoor = 5,
    OpenDoor = 6,
}

const NO_ITEM = 0;
const RANDOM_ITEM = 1;

const SMALL_MAP_PLAYERS = 2;
const MEDIUM_MAP_PLAYERS = 4;

const SIZE_SMALL_MAP = 10;
const SIZE_MEDIUM_MAP = 15;

const DEFAULT_DATE = new Date();
export const NEW_MAP_NO_ID = {
    name: 'map name',
    description: 'description of the map',
    visible: true,
    mode: 'normal',
    nbPlayers: SMALL_MAP_PLAYERS,
    image: 'image string',
    tiles: [
        [
            TileType.Ground,
            TileType.Ground,
            TileType.Ground,
            TileType.Ground,
            TileType.Ground,
            TileType.Ground,
            TileType.Ground,
            TileType.Ground,
            TileType.Ground,
            TileType.Ground,
        ],
        [
            TileType.Ground,
            TileType.Ground,
            TileType.Ground,
            TileType.Ground,
            TileType.Ground,
            TileType.Ground,
            TileType.Ground,
            TileType.Ground,
            TileType.Ground,
            TileType.Ground,
        ],
    ],
    dimension: SIZE_SMALL_MAP,
    itemPlacement: [
        [NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM],
        [NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM],
    ],
    isSelected: false,
    lastModification: DEFAULT_DATE,
};

export const EXISTING_MAP = {
    _id: '66f7162b7ec70b6faefa36fd',
    name: 'old name',
    description: 'old description',
    visible: true,
    mode: 'normal',
    nbPlayers: MEDIUM_MAP_PLAYERS,
    image: 'old image string',
    tiles: [
        [
            TileType.Water,
            TileType.Ice,
            TileType.Ground,
            TileType.Ice,
            TileType.Wall,
            TileType.OpenDoor,
            TileType.Ground,
            TileType.Ground,
            TileType.Water,
            TileType.Ice,
            TileType.Water,
            TileType.Ice,
            TileType.Wall,
            TileType.OpenDoor,
        ],
        [
            TileType.Water,
            TileType.Ice,
            TileType.Ground,
            TileType.Ice,
            TileType.Wall,
            TileType.OpenDoor,
            TileType.Ground,
            TileType.Ground,
            TileType.Water,
            TileType.Ice,
            TileType.Ground,
            TileType.Water,
            TileType.Ice,
            TileType.Wall,
        ],
    ],
    dimension: SIZE_MEDIUM_MAP,
    itemPlacement: [
        [
            NO_ITEM,
            RANDOM_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            RANDOM_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
        ],
        [
            NO_ITEM,
            RANDOM_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            RANDOM_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
        ],
    ],
    isSelected: false,
    lastModification: DEFAULT_DATE,
};

export const MAP_TO_PUT = {
    _id: '66f7162b7ec70b6faefa36fd',
    name: 'new name for the map',
    description: 'a different description than the last one',
    visible: true,
    mode: 'normal',
    nbPlayers: MEDIUM_MAP_PLAYERS,
    image: 'a new image to represent the tiles',
    tiles: [
        [
            TileType.Water,
            TileType.Ice,
            TileType.Ground,
            TileType.Ice,
            TileType.Wall,
            TileType.OpenDoor,
            TileType.Ground,
            TileType.Ground,
            TileType.Water,
            TileType.Ice,
            TileType.Water,
            TileType.Ice,
            TileType.Wall,
            TileType.OpenDoor,
        ],
        [
            TileType.Water,
            TileType.Ice,
            TileType.Ground,
            TileType.Ice,
            TileType.Wall,
            TileType.OpenDoor,
            TileType.Ground,
            TileType.Ground,
            TileType.Water,
            TileType.Ice,
            TileType.Ground,
            TileType.Water,
            TileType.Ice,
            TileType.Wall,
        ],
    ],
    dimension: SIZE_MEDIUM_MAP,
    itemPlacement: [
        [
            NO_ITEM,
            RANDOM_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            RANDOM_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
        ],
        [
            NO_ITEM,
            RANDOM_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            RANDOM_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
        ],
    ],
    isSelected: false,
    lastModification: DEFAULT_DATE,
};
