import { ITEM_COUNT, ObjectType } from '../client/src/app/constants';
import { GameObject } from './game-object';

export const gameObjects: GameObject[] = [
    {
        id: ObjectType.Trident,
        name: 'Trident de Poséidon',
        image: './assets/images/objects/poseidon-trident.jpg',
        description: "S'il vous reste un point d'action à la fin de votre tour, gagnez-en un à votre prochain tour, jusqu'à un maximum de 2.",
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Armor,
        name: "Armure d'Achilles",
        image: './assets/images/objects/armor-of-achilles.jpg',
        description: '+2 attaque, si votre attaque est bloquée, prenez 1 dégat.',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Sandal,
        name: 'Sandales ailées',
        image: './assets/images/objects/winged-sandals.jpg',
        description: 'x2 rapidité et réduit les points de vie maximaux de 1.',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Lightning,
        name: 'Foudre de Zeus',
        image: './assets/images/objects/zeus-lightning.jpg',
        description: 'x2 attaque et réduit la défense de 2 et la vie de 1.',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Xiphos,
        name: 'Xiphos',
        image: './assets/images/objects/xiphos.jpg',
        description: "Si vous avez moins de 50% de points de vie, votre adversaire perd 1 de défense et vous gagnez 2 d'attaque.",
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Kunee,
        name: 'Kunée',
        image: './assets/images/objects/helm-of-darkness.jpg',
        description: 'Permet de traverser les murs, ils sont considérés comme des tuiles avec un coût de 1.',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Random,
        name: 'Random Item',
        image: './assets/images/objects/dice.jpg',
        description: 'Ajoute un item aléatoire',
        count: -1,
    },
    {
        id: ObjectType.Spawn,
        name: 'Point de départ',
        image: './assets/images/objects/tree.jpg',
        description: 'Désigne le point de départ du jouer',
        count: -1,
    },
    {
        id: ObjectType.Flag,
        name: 'CTF Flag',
        image: './assets/images/objects/flag.jpg',
        description: 'Drapeau pour le mode CTF',
        count: ITEM_COUNT,
    },
    {
        id: ObjectType.Hestia,
        name: 'Hestia',
        image: './assets/images/characters/Hestia.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Zeus,
        name: 'Zeus',
        image: './assets/images/characters/Zeus.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Hera,
        name: 'Hera',
        image: './assets/images/characters/Hera.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Poseidon,
        name: 'Poseidon',
        image: './assets/images/characters/Poseidon.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Artemis,
        name: 'Artemis',
        image: './assets/images/characters/Artemis.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Demeter,
        name: 'Demeter',
        image: './assets/images/characters/Demeter.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Hermes,
        name: 'Hermes',
        image: './assets/images/characters/Hermes.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Athena,
        name: 'Athena',
        image: './assets/images/characters/Athena.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Hephaestus,
        name: 'Hephaestus',
        image: './assets/images/characters/Hephaestus.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Apollo,
        name: 'Apollo',
        image: './assets/images/characters/Apollo.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Ares,
        name: 'Ares',
        image: './assets/images/characters/Ares.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
    {
        id: ObjectType.Aphrodite,
        name: 'Aphrodite',
        image: './assets/images/characters/Aphrodite.webp',
        description: 'Photo de Hestia',
        count: -1,
    },
];
