const GROUND_TILE = 1;
const WATER_TILE = 2;
const ICE_TILE = 3;
const WALL_TILE = 4;
const DOOR_TILE = 5;

const NO_ITEM = 0;
const RANDOM_ITEM = 1;

const SMALL_MAP_PLAYERS = 2;
const MEDIUM_MAP_PLAYERS = 4;

const SIZE_SMALL_MAP = 10;
const SIZE_MEDIUM_MAP = 15;

const DEFAULT_DATE = new Date();
export const NEW_MAP_NO_ID = {
    name: 'map name',
    description: 'description of the map',
    visible: true,
    mode: 'normal',
    nbPlayers: SMALL_MAP_PLAYERS,
    image: 'image string',
    tiles: [
        [GROUND_TILE, GROUND_TILE, GROUND_TILE, GROUND_TILE, GROUND_TILE, GROUND_TILE, GROUND_TILE, GROUND_TILE, GROUND_TILE, GROUND_TILE],
        [GROUND_TILE, GROUND_TILE, GROUND_TILE, GROUND_TILE, GROUND_TILE, GROUND_TILE, GROUND_TILE, GROUND_TILE, GROUND_TILE, GROUND_TILE],
    ],
    dimension: SIZE_SMALL_MAP,
    itemPlacement: [
        [NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM],
        [NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM, NO_ITEM],
    ],
    isSelected: false,
    lastModification: DEFAULT_DATE,
};

export const EXISTING_MAP = {
    _id: '66f7162b7ec70b6faefa36fd',
    name: 'old name',
    description: 'old description',
    visible: true,
    mode: 'normal',
    nbPlayers: MEDIUM_MAP_PLAYERS,
    image: 'old image string',
    tiles: [
        [
            WATER_TILE,
            ICE_TILE,
            GROUND_TILE,
            ICE_TILE,
            WALL_TILE,
            DOOR_TILE,
            GROUND_TILE,
            GROUND_TILE,
            WATER_TILE,
            ICE_TILE,
            WATER_TILE,
            ICE_TILE,
            WALL_TILE,
            DOOR_TILE,
        ],
        [
            WATER_TILE,
            ICE_TILE,
            GROUND_TILE,
            ICE_TILE,
            WALL_TILE,
            DOOR_TILE,
            GROUND_TILE,
            GROUND_TILE,
            WATER_TILE,
            ICE_TILE,
            GROUND_TILE,
            WATER_TILE,
            ICE_TILE,
            WALL_TILE,
        ],
    ],
    dimension: SIZE_MEDIUM_MAP,
    itemPlacement: [
        [
            NO_ITEM,
            RANDOM_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            RANDOM_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
        ],
        [
            NO_ITEM,
            RANDOM_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            RANDOM_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
        ],
    ],
    isSelected: false,
    lastModification: DEFAULT_DATE,
};

export const MAP_TO_PUT = {
    _id: '66f7162b7ec70b6faefa36fd',
    name: 'new name for the map',
    description: 'a different description than the last one',
    visible: true,
    mode: 'normal',
    nbPlayers: MEDIUM_MAP_PLAYERS,
    image: 'a new image to represent the tiles',
    tiles: [
        [
            WATER_TILE,
            ICE_TILE,
            GROUND_TILE,
            ICE_TILE,
            WALL_TILE,
            DOOR_TILE,
            GROUND_TILE,
            GROUND_TILE,
            WATER_TILE,
            ICE_TILE,
            WATER_TILE,
            ICE_TILE,
            WALL_TILE,
            DOOR_TILE,
        ],
        [
            WATER_TILE,
            ICE_TILE,
            GROUND_TILE,
            ICE_TILE,
            WALL_TILE,
            DOOR_TILE,
            GROUND_TILE,
            GROUND_TILE,
            WATER_TILE,
            ICE_TILE,
            GROUND_TILE,
            WATER_TILE,
            ICE_TILE,
            WALL_TILE,
        ],
    ],
    dimension: SIZE_MEDIUM_MAP,
    itemPlacement: [
        [
            NO_ITEM,
            RANDOM_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            RANDOM_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
        ],
        [
            NO_ITEM,
            RANDOM_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
            RANDOM_ITEM,
            NO_ITEM,
            NO_ITEM,
            NO_ITEM,
        ],
    ],
    isSelected: false,
    lastModification: DEFAULT_DATE,
};
